QLCuaHangThoiTrang/CHBHTH/Models/SanPham63133125.cs
namespace QLCuaHangThoiTrang_63133125.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SanPham")]
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }

        [Display(Name = "Mã sản phẩm")]
        [Key]
        public int MaSP { get; set; }

        [Display(Name = "Tên sản phẩm")]
        [StringLength(100)]
        public string TenSP { get; set; }

        [Display(Name = "Giá bán")]
        public decimal? GiaBan { get; set; }

        [Display(Name = "Số lượng")]
        public int? SoLuong { get; set; }

        [Display(Name = "Mô tả")]
        [Column(TypeName = "ntext")]
        public string MoTa { get; set; }

        [Display(Name = "Mã loại")]
        public int? MaLoai { get; set; }

        [Display(Name = "Nhà cung cấp")]
        public int? MaNCC { get; set; }

        [Display(Name = "Ảnh sản phẩm")]
        
        public string AnhSP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

        public virtual LoaiHang LoaiHang { get; set; }

        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}

QLCuaHangThoiTrang/CHBHTH/Controllers/GioHang63133125Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLCuaHangThoiTrang_63133125.Models;

namespace QLCuaHangThoiTrang_63133125.Controllers
{
    public class GioHang63133125Controller : Controller
    {
        private QLbanhang db = new QLbanhang();
        // GET: GioHang
        //Lấy giỏ hàng 
        public List<GioHang> LayGioHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang == null)
            {
                //Nếu giỏ hàng chưa tồn tại thì mình tiến hành khởi tao list giỏ hàng (sessionGioHang)
                lstGioHang = new List<GioHang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }
        //Thêm giỏ hàng
        public ActionResult ThemGioHang(int iMasp, string strURL)
        {
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == iMasp);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy ra session giỏ hàng
            List<GioHang> lstGioHang = LayGioHang();
            //Kiểm tra sp này đã tồn tại trong session[giohang] chưa
            GioHang sanpham = lstGioHang.Find(n => n.iMasp == iMasp);
            if (sanpham == null)
            {
                sanpham = new GioHang(iMasp);
                //Add sản phẩm mới thêm vào list
                lstGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoLuong++;
                return Redirect(strURL);
            }
        }
        //Cập nhật giỏ hàng 
        public ActionResult CapNhatGioHang(int iMaSP, FormCollection f)
        {
            //Kiểm tra masp
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == iMaSP);
            //Nếu get sai masp thì sẽ trả về trang lỗi 404
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy giỏ hàng ra từ session
            List<GioHang> lstGioHang = LayGioHang();
            //Kiểm tra sp có tồn tại trong session["GioHang"]
            GioHang sanpham = lstGioHang.SingleOrDefault(n => n.iMasp == iMaSP);
            //Nếu mà tồn tại thì chúng ta cho sửa số lượng
            if (sanpham != null)
            {
                sanpham.iSoLuong = int.Parse(f["txtSoLuong"].ToString());

            }
            return RedirectToAction("GioHang");
        }
        //Xóa giỏ hàng
        public ActionResult XoaGioHang(int iMaSP)
        {
            //Kiểm tra masp
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == iMaSP);
            //Nếu get sai masp thì sẽ trả về trang lỗi 404
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy giỏ hàng ra từ session
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sanpham = lstGioHang.SingleOrDefault(n => n.iMasp == iMaSP);
            //Nếu mà tồn tại thì chúng ta cho sửa số lượng
            if (sanpham != null)
            {
                lstGioHang.RemoveAll(n => n.iMasp == iMaSP);

            }
            if (lstGioHang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang");
        }
        //Xây dựng trang giỏ hàng
        public ActionResult GioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            return View(lstGioHang);
        }
        //Tính tổng số lượng và tổng tiền
        //Tính tổng số lượng
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.iSoLuong);
            }
            return iTongSoLuong;
        }
        //Tính tổng thành tiền
        private double TongTien()
        {
            double dTongTien = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                dTongTien = lstGioHang.Sum(n => n.ThanhTien);
            }
            return dTongTien;
        }
        //tạo partial giỏ hàng
        public ActionResult GioHangPartial()
        {
            if (TongSoLuong() == 0)
            {
                return PartialView();
            }
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }
        //Xây dựng 1 view cho người dùng chỉnh sửa giỏ hàng
        public ActionResult SuaGioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            return View(lstGioHang);

        }

        #region 
        //Xây dựng chức năng đặt hàng
        [HttpPost]
        public ActionResult DatHang(FormCollection donhangForm)
        {
            //Kiểm tra đăng nhập
            if (Session["use"] == null || Session["use"].ToString() == "")
            {
                return RedirectToAction("Dangnhap", "User63133125");
            }
            //Kiểm tra giỏ hàng
            if (Session["GioHang"] == null)
            {
                RedirectToAction("Index", "Home");
            }
            Console.WriteLine(donhangForm);
            string diachinhanhang = donhangForm["DiaChiNhanHang"].ToString();
            string thanhtoan = donhangForm["MaTT"].ToString();
            int ptthanhtoan = Int32.Parse(thanhtoan);

            //Thêm đơn hàng
            DonHang ddh = new DonHang();
            TaiKhoan kh = (TaiKhoan)Session["use"];
            List<GioHang> gh = LayGioHang();
            ddh.MaNguoiDung = kh.MaNguoiDung;
            ddh.NgayDat = DateTime.Now;
            ddh.ThanhToan = ptthanhtoan;
            ddh.DiaChiNhanHang = diachinhanhang;
            decimal tongtien = 0;
            foreach (var item in gh)
            {
                decimal thanhtien = item.iSoLuong * (decimal)item.dDonGia;
                tongtien += thanhtien;
            }
            ddh.TongTien = tongtien;
            db.DonHangs.Add(ddh);
            db.SaveChanges();
            //Thêm chi tiết đơn hàng
            foreach (var item in gh)
            {
                ChiTietDonHang ctDH = new ChiTietDonHang();
                decimal thanhtien = item.iSoLuong * (decimal)item.dDonGia;
                ctDH.MaDon = ddh.MaDon;
                ctDH.MaSP = item.iMasp;
                ctDH.SoLuong = item.iSoLuong;
                ctDH.DonGia = (decimal)item.dDonGia;
                ctDH.ThanhTien = (decimal)thanhtien;
                ctDH.PhuongThucThanhToan = 1;
                db.ChiTietDonHangs.Add(ctDH);
            }
            db.SaveChanges();
            return RedirectToAction("Index", "Donhangs63133125");
        }
        #endregion

        public ActionResult ThanhToanDonHang()
        {

            ViewBag.MaTT = new SelectList(new[]
                {
                    new { MaTT = 1, TenPT="Thanh toán tiền mặt" },
                    new { MaTT = 2, TenPT="Thanh toán chuyển khoản" },
                }, "MaTT", "TenPT", 1);
            ViewBag.MaNguoiDung = new SelectList(db.TaiKhoans, "MaNguoiDung", "HoTen");

            //Kiểm tra đăng đăng nhập
            if (Session["use"] == null || Session["use"].ToString() == "")
            {
                return RedirectToAction("Dangnhap", "User63133125");
            }
            //Kiểm tra giỏ hàng
            if (Session["GioHang"] == null)
            {
                RedirectToAction("Index", "Home");
            }
            //Thêm đơn hàng
            DonHang ddh = new DonHang();
            TaiKhoan kh = (TaiKhoan)Session["use"];
            List<GioHang> gh = LayGioHang();
            decimal tongtien = 0;
            foreach (var item in gh)
            {
                decimal thanhtien = item.iSoLuong * (decimal)item.dDonGia;
                tongtien += thanhtien;
            }

            ddh.MaNguoiDung = kh.MaNguoiDung;
            ddh.NgayDat = DateTime.Now;
            ChiTietDonHang ctDH = new ChiTietDonHang();
            ViewBag.tongtien = tongtien;
            return View(ddh);

        }

    }
}

QLCuaHangThoiTrang/CHBHTH/Controllers/sanpham63133125Controller.cs
using QLCuaHangThoiTrang_63133125.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace QLCuaHangThoiTrang_63133125.Controllers
{
    public class sanpham63133125Controller : Controller
    {
        private QLbanhang db = new QLbanhang();
        // GET: sanpham
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiHang).Include(s => s.NhaCungCap);
            return View(sanPhams.ToList());
        }

        public ActionResult suapartial()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 1).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult raupartial()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 2).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult dauanpartial()  
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 3).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult xemchitiet(int Masp = 0)
        {
            var chitiet = db.SanPhams.SingleOrDefault(n => n.MaSP == Masp);
            if (chitiet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(chitiet);
        }


        public ActionResult xemchitietdanhmuc(int MaLoai)
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == MaLoai).ToList();
            return PartialView(ip);

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLCuaHangThoiTrang/CHBHTH/Views/sanpham63133125/Index.cshtml
@model IEnumerable<QLCuaHangThoiTrang_63133125.Models.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}

<section class="py-1">
    <center> <h3 style="color: #CC9966;"> Tất cả sản phẩm </h3> </center>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <a href="@Url.Action("xemchitiet", new {@MaSP=item.MaSP })">
                            <center>
                                <img src="/Images/@Html.DisplayFor(model => item.AnhSP)" class="img-responsive" alt="" width="200" height="150" />
                            </center>
                        </a>
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">@item.TenSP</h5>
                                <!-- Product price-->
                                Giá: @String.Format("{0:0,0}", @item.GiaBan) VND
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                @using (Html.BeginForm("ThemGioHang", "GioHang63133125", new { @iMaSP = item.MaSP, @strURL = Request.Url.ToString() }))
                                {
                                    <input type="submit" value="Thêm vào giỏ hàng" id="bgnGioHang" class="btn btn-outline-dark mt-auto" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

QLCuaHangThoiTrang/CHBHTH/Views/sanpham63133125/dauanpartial.cshtml
@using QLCuaHangThoiTrang_63133125.Models;
@model List<SanPham>

<section class="py-1">
    <center> <h3 style="color: #CC9966;"> Các mẫu quần bán chạy  </h3> </center>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                @foreach (var item in Model)
                {
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <a href="@Url.Action("xemchitiet", new {@MaSP=item.MaSP })">
                                <center>
                                    <img src="/Images/@Html.DisplayFor(model => item.AnhSP)" class="img-responsive" alt="" width="200" height="150" />
                                </center>
                            </a>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">@item.TenSP</h5>
                                    <!-- Product price-->
                                    Giá: @String.Format("{0:0,0}", @item.GiaBan) VND
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    @using (Html.BeginForm("ThemGioHang", "GioHang63133125", new { @iMaSP = item.MaSP, @strURL = Request.Url.ToString() }))
                                    {
                                        <input type="submit" value="Thêm vào giỏ hàng" id="bgnGioHang" class="btn btn-outline-dark mt-auto" />
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
</section>
  

QLCuaHangThoiTrang/CHBHTH/Views/sanpham63133125/raupartial.cshtml
@using QLCuaHangThoiTrang_63133125.Models;
@model List<SanPham>

<section class="py-1">
    <center> <h3 style="color: #CC9966;"> Các mẫu áo thun bán chạy </h3> </center>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <a href="@Url.Action("xemchitiet", new {@MaSP=item.MaSP })">
                            <center>
                                <img src="/Images/@Html.DisplayFor(model => item.AnhSP)" class="img-responsive" alt="" width="200" height="150" />
                            </center>
                        </a>
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">@item.TenSP</h5>
                                <!-- Product price-->
                                Giá: @String.Format("{0:0,0}", @item.GiaBan) VND
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                @using (Html.BeginForm("ThemGioHang", "GioHang63133125", new { @iMaSP = item.MaSP, @strURL = Request.Url.ToString() }))
                                {
                                    <input type="submit" value="Thêm vào giỏ hàng" id="bgnGioHang" class="btn btn-outline-dark mt-auto" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

QLCuaHangThoiTrang/CHBHTH/Views/sanpham63133125/suapartial.cshtml
@using QLCuaHangThoiTrang_63133125.Models;
@model List<SanPham>

<section class="py-1">
    <center> <h3 style="color: #CC9966;"> Các mẫu váy bán chạy </h3> </center>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <a href="@Url.Action("xemchitiet", new {@MaSP=item.MaSP })">
                            <center>
                                <img src="/Images/@Html.DisplayFor(model => item.AnhSP)" class="img-responsive" alt="" width="200" height="150" />
                            </center>
                        </a>
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">@item.TenSP</h5>
                                <!-- Product price-->
                                Giá: @String.Format("{0:0,0}", @item.GiaBan) VND
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                @using (Html.BeginForm("ThemGioHang", "GioHang63133125", new { @iMaSP = item.MaSP, @strURL = Request.Url.ToString() }))
                                {
                                    <input type="submit" value="Thêm vào giỏ hàng" id="bgnGioHang" class="btn btn-outline-dark mt-auto" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

QLCuaHangThoiTrang/CHBHTH/Views/sanpham63133125/xemchitiet.cshtml
@using QLCuaHangThoiTrang_63133125.Models
@model  SanPham

@{
    ViewBag.Title = "xemchitiet";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}
<section class="py-0">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="/Images/@Html.DisplayFor(model => model.AnhSP)" alt="" /></div>
            <div class="col-md-6">
                <div class="small mb-1">Loại hàng:  @Model.LoaiHang.TenLoai</div>
                <div class="small mb-1">Nhà cung cấp: @Model.NhaCungCap.TenNCC</div>
                <h1 class="display-5 fw-bolder">@Model.TenSP </h1>
                <div class="fs-5 mb-5">
                    <span> Giá: @String.Format("{0:0,0}", @Model.GiaBan) VNĐ </span>
                </div>
                Mô tả sản phẩm:
                <p class="lead"> @Model.MoTa </p>
                <div class="d-flex">
                   
                        @using (Html.BeginForm("ThemGioHang", "GioHang63133125", new { @iMaSP = Model.MaSP, @strURL = Request.Url.ToString() }))
                        {
                            <i class="bi-cart-fill me-1"></i>
                            <input type="submit" value="Thêm vào giỏ hàng" id="bgnGioHang" class="btn btn-outline-dark flex-shrink-0" />

                        }

                </div>
            </div>
        </div>
    </div>
</section>

QLCuaHangThoiTrang/CHBHTH/Views/sanpham63133125/xemchitietdanhmuc.cshtml
@using QLCuaHangThoiTrang_63133125.Models;
@model List<SanPham>

@{
    ViewBag.Title = "xemchitietdanhmuc";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}


<section class="py-1">
    <center> <h3 style="color: #CC9966;"> Danh mục sản phẩm </h3> </center>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <a href="@Url.Action("xemchitiet", new {@MaSP=item.MaSP })">
                            <center>
                                <img src="/Images/@Html.DisplayFor(model => item.AnhSP)" class="img-responsive" alt="" width="200" height="150" />
                            </center>
                        </a>
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">@item.TenSP</h5>
                                <!-- Product price-->
                                Giá: @String.Format("{0:0,0}", @item.GiaBan) VND
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                @using (Html.BeginForm("ThemGioHang", "GioHang63133125", new { @iMaSP = item.MaSP, @strURL = Request.Url.ToString() }))
                                {
                                    <input type="submit" value="Thêm vào giỏ hàng" id="bgnGioHang" class="btn btn-outline-dark mt-auto" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>