QLCuaHangThoiTrang/CHBHTH/Areas/Admin/Controllers/SanPhams63133125Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLCuaHangThoiTrang_63133125.Models;
using PagedList;

namespace QLCuaHangThoiTrang_63133125.Areas.Admin.Controllers

{
    public class SanPhams63133125Controller : Controller
    {
        private QLbanhang db = new QLbanhang();

        // GET: SanPhams
        public ActionResult Index(string searchString)
        {
            ViewBag.SearchString = searchString;

            var sanPhams = db.SanPhams.Include(s => s.LoaiHang).Include(s => s.NhaCungCap);

            // Filter by product name if searchString is not empty
            if (!string.IsNullOrEmpty(searchString))
            {
                sanPhams = sanPhams.Where(s => s.TenSP.Contains(searchString));
            }

            var u = Session["use"] as QLCuaHangThoiTrang_63133125.Models.TaiKhoan;
            if (u.PhanQuyen.TenQuyen == "Adminstrator")
            {
                return View(sanPhams.OrderByDescending(s => s.MaSP).ToList());
            }

            return RedirectPermanent("~/Home/Index");
        }


        // GET: SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai");
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,GiaBan,SoLuong,MoTa,MaLoai,MaNCC,AnhSP")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", sanPham.MaNCC);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", sanPham.MaNCC);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,GiaBan,SoLuong,MoTa,MaLoai,MaNCC,AnhSP")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", sanPham.MaNCC);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLCuaHangThoiTrang/CHBHTH/Areas/Admin/Views/SanPhams63133125/Create.cshtml
@model QLCuaHangThoiTrang_63133125.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Tạo sản phẩm</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>
  
        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>
     
        <div class="form-group">
            @Html.LabelFor(model => model.MaLoai, "Loại hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
            </div>
        </div>
   
        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, "Tên nhà cung cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
            @Html.LabelFor(model => model.AnhSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhSP, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.AnhSP, "", new { @class = "text-danger" })
            </div>
        </div>
     
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<br />
<div>
    @Html.ActionLink("Trở về", "Index")
</div>
    

QLCuaHangThoiTrang/CHBHTH/Areas/Admin/Views/SanPhams63133125/Delete.cshtml
@model QLCuaHangThoiTrang_63133125.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Xóa sản phẩm</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LoaiHang.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiHang.TenLoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaCungCap.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaCungCap.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @String.Format("{0:0,0}", Model.GiaBan) VNĐ
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhSP)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.AnhSP)" width="200px" height="150px" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" />
        </div>
    }
    <br />
    @Html.ActionLink("Trở về", "Index")
</div>

QLCuaHangThoiTrang/CHBHTH/Areas/Admin/Views/SanPhams63133125/Details.cshtml
@model QLCuaHangThoiTrang_63133125.Models.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết sản phẩm</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LoaiHang.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiHang.TenLoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaCungCap.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaCungCap.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @String.Format("{0:0,0}", Model.GiaBan) VNĐ
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhSP)
        </dt>

        <dd>
            <img src="/Images/@Html.DisplayFor(model => model.AnhSP)" width="200px" height="150px" />
        </dd>

    </dl>
</div>
<button class="btn btn-danger">
    @Html.ActionLink("Xóa", "Delete", new { id = Model.MaSP }, new { @style = "color:white;" })
</button>

<button class="btn btn-success">
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaSP }, new { @style = "color:white;" })
</button>
<br />
<br />
<p>
    @Html.ActionLink("Trở về", "Index")
</p>

QLCuaHangThoiTrang/CHBHTH/Areas/Admin/Views/SanPhams63133125/Edit.cshtml
@model QLCuaHangThoiTrang_63133125.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sửa sản phẩm</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSP)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>
 
        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>
  
        <div class="form-group">
            @Html.LabelFor(model => model.MaLoai, "Tên loại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
            </div>
        </div>
 
        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, "Tên nhà cung cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea class="form-control" name="MoTa" > @Model.MoTa </textarea>
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>
   
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<br />
<div>
    @Html.ActionLink("Trở về", "Index")
</div>

QLCuaHangThoiTrang/CHBHTH/Areas/Admin/Views/SanPhams63133125/Index.cshtml
@model IEnumerable<QLCuaHangThoiTrang_63133125.Models.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "id", rowsPerPage: 5);
}

<h2>Sản phẩm</h2>

<p>
    @Html.ActionLink("Tạo sản phẩm", "Create")
</p>
<div>
    @using (Html.BeginForm("Index", "SanPhams63133125", FormMethod.Get))
    {
        <input type="text" name="searchString" placeholder="Nhập tên sản phẩm cần tìm" value="@ViewBag.SearchString" />
        <button type="submit">Search</button>
    }
</div>
<div class="grid-container">
    @grid.GetHtml(
        tableStyle: "table table-bordered",
        headerStyle: "webgrid-header",
        footerStyle: "webgrid-footer",
        alternatingRowStyle: "webgrid-alternating-row",
        selectedRowStyle: "webgrid-selected-row",
        rowStyle: "webgrid-row-style",
        columns: grid.Columns(
            grid.Column("TenSP", header: "Tên Sản Phẩm", style: ""),
            grid.Column("LoaiHang.TenLoai", header: "Loại Hàng", style: ""),
            grid.Column("NhaCungCap.TenNCC", header: "Nhà Cung Cấp", style: ""),
            grid.Column("GiaBan", header: "Giá Bán", style: ""),
            grid.Column("SoLuong", header: "Số Lượng", style: ""),
            grid.Column("MoTa", header: "Mô Tả", style: ""),
            grid.Column(header: "", format: @<text>
                    @Html.ActionLink("Xem", "Details", new { id = item.MaSP }, new { @style = "color: blue;" })
            </text>)
)
)
</div>
<style>
    .unclickable-header {
        pointer-events: none;
        cursor: default;
    }

    .webgrid-footer a {
        display: inline-block;
        padding: 6px 12px;
        margin: 2px;
        font-size: 16px;
        line-height: 1.5;
        background-color: #007bff;
        border: 1px solid #007bff;
        color: #fff;
        text-decoration: none;
        border-radius: 4px;
    }

    .webgrid-footer .webgrid-page {
        margin: 2px;
    }

    .webgrid-footer a:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }

    .webgrid-footer .webgrid-selected-page {
        background-color: #0056b3;
        border-color: #0056b3;
        color: #fff;
    }
</style>