QLCuaHangThoiTrang/CHBHTH/Areas/Admin/Controllers/HomeController.cs
using QLCuaHangThoiTrang_63133125.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace QLCuaHangThoiTrang_63133125.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {

        // GET: Admin/Home
        public ActionResult Index()
        {
            var u = Session["use"] as QLCuaHangThoiTrang_63133125.Models.TaiKhoan;
            //Kiểm tra nếu tên quyền Administrator mới được truy cập trang admin
            if(u.PhanQuyen.TenQuyen == "Adminstrator")
            {
                return View();
            }

            return RedirectPermanent("~/Home/Index");
        }
    }
}

QLCuaHangThoiTrang/CHBHTH/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLCuaHangThoiTrang_63133125.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {

            return View();
        }

        public ActionResult SlidePartial()
        {
            return PartialView();

        }

        public ActionResult Trangchu()
        {
            return View();

        }

        public ActionResult login()
        {
            return View();

        }
    }
}

QLCuaHangThoiTrang/CHBHTH/Controllers/sanpham63133125Controller.cs
using QLCuaHangThoiTrang_63133125.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace QLCuaHangThoiTrang_63133125.Controllers
{
    public class sanpham63133125Controller : Controller
    {
        private QLbanhang db = new QLbanhang();
        // GET: sanpham
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiHang).Include(s => s.NhaCungCap);
            return View(sanPhams.ToList());
        }

        public ActionResult suapartial()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 1).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult raupartial()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 2).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult dauanpartial()  
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 3).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult xemchitiet(int Masp = 0)
        {
            var chitiet = db.SanPhams.SingleOrDefault(n => n.MaSP == Masp);
            if (chitiet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(chitiet);
        }


        public ActionResult xemchitietdanhmuc(int MaLoai)
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == MaLoai).ToList();
            return PartialView(ip);

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLCuaHangThoiTrang/CHBHTH/Views/Home/About.cshtml
@{
    ViewBag.Title = "Giới Thiệu";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}

<style>
    main {
        background-color: #f8f9fa;
        color: #343a40;
        padding: 40px 0;
    }

    h2, h3 {
        color: #CC9966;
    }

    p {
        line-height: 1.6;
    }

    ul {
        list-style-type: disc;
        margin-left: 20px;
    }

    li {
        margin-bottom: 10px;
    }

    /* Container Styles */
    .container {
        margin: 0 auto;
    }
    ul li {
        list-style: none;
    }
</style>

<main aria-labelledby="title">
    <div class="container">
        <h3>Chào mừng bạn đến với Cửa hàng Thời trang Nam Nữ VNZClothers-Shop!</h3>

        <p>Khám phá phong cách thời trang đỉnh cao và trải nghiệm một thế giới của sự sành điệu tại cửa hàng thời trang trực tuyến của chúng tôi. Chúng tôi không chỉ là một nơi mua sắm; chúng tôi là một cộng đồng tôn vinh sự sáng tạo, phong cách và sự tự tin.</p>

        <p>Tại VNZClothers-Shop, chúng tôi tự hào mang đến cho bạn một lựa chọn phong phú những trang phục và phụ kiện thời trang phục vụ mọi nhu cầu và phong cách. Cho dù bạn là một người đam mê thời trang, một người theo đuổi xu hướng, hoặc ai đó đang tìm kiếm các lựa chọn phù hợp với ngân sách, chúng tôi có một cái gì đó cho mọi người.</p>

        <p>Tại sao chọn chúng tôi?</p>
        <ul>
            <li><strong>Đa dạng không giới hạn:</strong> Khám phá một loạt các sản phẩm thời trang từ các thương hiệu hàng đầu.</li>
            <li><strong>Ưu đãi độc quyền:</strong> Thưởng thức những ưu đãi và khuyến mãi đặc biệt dành cho cộng đồng của chúng tôi.</li>
            <li><strong>Đánh giá của chuyên gia:</strong> Đưa ra quyết định thông minh với những đánh giá sản phẩm và hướng dẫn phong cách chi tiết của chúng tôi.</li>
            <li><strong>Mua sắm an toàn:</strong> Mua sắm với sự tự tin khi biết rằng quyền riêng tư và bảo mật của bạn là ưu tiên hàng đầu của chúng tôi.</li>
        </ul>

        <p>Hãy tham gia với chúng tôi trong chuyến phiêu lưu này của khám phá thời trang, nơi mỗi cú nhấp chuột đưa bạn gần hơn với phong cách hoàn hảo. Cảm nhận sự hứng thú từ những bộ sưu tập mới nhất, cập nhật xu hướng thời trang và trở thành một phần của cộng đồng yêu thời trang chung của chúng tôi.</p>

        <p>Cảm ơn bạn đã chọn VNZClothers-Shop. Hành trình của bạn vào thế giới thời trang bắt đầu từ đây!</p>

    </div>
</main>

QLCuaHangThoiTrang/CHBHTH/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Liên hệ";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}
<style>
    main {
        background-color: #f8f9fa;
        color: #343a40;
        padding: 40px 0;
    }


    p {
        line-height: 1.6;
    }

    ul {
        list-style-type: disc;
        margin-left: 20px;
    }

    li {
        margin-bottom: 10px;
    }
    /* Container Styles */
    .container {
        margin: 0 auto;
    }

    ul li {
        list-style: none;
    }
</style>
<main aria-labelledby="title">
    <div class="container">
        <h2 id="title" style="color: #CC9966;">@ViewBag.Title</h2>

        <div style="margin-top: 20px;">
            <address style="margin-bottom: 15px;">
                <strong>Lê Đoàn Quốc Văn</strong><br />
                MSV: VNZClothers-Shop<br />
                <abbr title="Phone">Phone:</abbr> 0869604227
                Mail: vanyus1505@gmail.com
            </address>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d59597.1444449174!2d105.74882892815583!3d20.99979007593677!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454cabc683f57%3A0xdb02223a0620af21!2zxJDhuqFpIGjhu41jIE5ndXnhu4VuIFRyw6Np!5e0!3m2!1svi!2s!4v1731601162548!5m2!1svi!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>        </div>
    </div>
</main>

QLCuaHangThoiTrang/CHBHTH/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Molla";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}
@using QLCuaHangThoiTrang_63133125.Models;

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!-- Google fonts-->
    
    <style>
        /* Header Styles */
        header {
            background-color: #333;
            color: white;
            padding: 10px;
        }

            header img {
                max-width: 100%;
                height: auto;
            }

        /* Featured Images Styles */
        .spnoibat {
            margin-top: 20px;
        }

            .spnoibat img {
                border: 2px solid #ddd;
                border-radius: 8px;
                margin-bottom: 15px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            }

                .spnoibat img:hover {
                    transform: scale(1.05);
                    transition: transform 0.3s ease-in-out;
                }

        /* Centered Content Styles */
        .text-center {
            text-align: center;
        }

        /* Responsive Design */
        img.img-responsive {
            max-width: 100%;
            height: auto;
        }

        /* Vibrant Colors */
        body {
            background-color: #f8f9fa;
            color: #343a40;
        }



        .spnoibat img {
            animation: fadeIn 1s ease-in-out;
        }
        ul li {
            list-style-type: none;
        }
    </style>
    <title>VNZClothers-Shop</title>
</head>
<body>
 

    <br />
    <header class="bg-body py-0">
        <center>
            <div class="container">
                <div class="col-lg-12 col-md-8">
                    <img src="~/Images/trangchu2.jpg" />
                </div>
            </div>
        </center>
    </header>
    <br />
    <div class="spnoibat">
        <center>
            <div class="row">
                <div class="col-md-4">
                    <img src="~/Images/" class="img-responsive" alt=""/>
                </div>
                <div class="col-md-4">
                    <img src="~/Images/" class="img-responsive" alt=""/>
                </div>
                <div class="col-md-4">
                    <img src="~/Images/" class="img-responsive" alt=""/>
                </div>
            </div>
        </center>
    </div>
    <br />

    @Html.Action("suapartial", "sanpham63133125")

    @Html.Action("dauanpartial", "sanpham63133125")
    <div class="bg-body py-0">
        <center>
            <div class="container">
                <div class="col-lg-12 col-md-8">
                    <img src="~/Images/TRANG-CHU-2.svg" />
                </div>
            </div>
        </center>
    </div>
    <br />

    @Html.Action("raupartial", "sanpham63133125")

</body>
</html>