QLCuaHangThoiTrang/CHBHTH/Controllers/Donhangs63133125Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLCuaHangThoiTrang_63133125.Models;

namespace QLCuaHangThoiTrang_63133125.Controllers
{
    public class Donhangs63133125Controller : Controller
    {
        private QLbanhang db = new QLbanhang();

        // GET: Donhangs
        // Hiển thị danh sách đơn hàng
        public ActionResult Index()
        {
            //Kiểm tra đang đăng nhập
            if (Session["use"] == null || Session["use"].ToString() == "")
            {
                return RedirectToAction("Dangnhap", "User63133125");
            }
            TaiKhoan kh = (TaiKhoan)Session["use"];
            int maND = kh.MaNguoiDung;
            var donhangs = db.DonHangs.Include(d => d.TaiKhoan).Where(d => d.MaNguoiDung == maND);
            return View(donhangs.ToList());
        }

        // GET: Donhangs/Details/5
        //Hiển thị chi tiết đơn hàng
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            var chitiet = db.ChiTietDonHangs.Include(d => d.SanPham).Where(d => d.MaDon == id).ToList();
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(chitiet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLCuaHangThoiTrang/CHBHTH/Controllers/User63133125Controller.cs
using QLCuaHangThoiTrang_63133125.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QLCuaHangThoiTrang_63133125.Controllers
{
    public class User63133125Controller : Controller
    {
        QLbanhang db = new QLbanhang();

        // ĐĂNG KÝ
        public ActionResult Dangky()
        {
            return View();
        }

        // ĐĂNG KÝ PHƯƠNG THỨC POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Dangky(TaiKhoan taiKhoan)
        {
            try
            {
                Session["userReg"] = taiKhoan;


                // Nếu dữ liệu đúng thì trả về trang đăng nhập
                if (ModelState.IsValid)
                {
                    var check = db.TaiKhoans.FirstOrDefault(s => s.Email == taiKhoan.Email);
                    if (check == null)
                    {
                        //return RedirectToAction("Dangnhap");
                        ViewBag.RegOk = "Đăng kí thành công. Đăng nhập ngay";
                        ViewBag.isReg = true;
                        // Thêm người dùng  mới
                        db.TaiKhoans.Add(taiKhoan);
                        // Lưu lại vào cơ sở dữ liệu
                        db.SaveChanges();
                        return View("Dangky");
                    }
                    else
                    {
                        ViewBag.RegOk = "Email đã tồn tại! Vui lòng chọn 1 email khác";
                        return View("Dangky");
                    }

                }
                {
                    return View("Dangky");
                }
                    

            }
            catch
            {
                return View();
            }
        }

        [AllowAnonymous]
        public ActionResult Dangnhap()
        {
            return View();

        }


        [HttpPost]
        public ActionResult Dangnhap(FormCollection userlog)
        {
            string userMail = userlog["userMail"].ToString();
            string password = userlog["password"].ToString();
            var islogin = db.TaiKhoans.FirstOrDefault(x => x.Email.Equals(userMail) && x.MatKhau.Equals(password));

            if (islogin != null)
            {
                if (userMail == "admin@gmail.com")
                {
                    Session["use"] = islogin;
                    return RedirectToAction("Index", "Admin/Home");
                }
                else
                {
                    Session["use"] = islogin;
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewBag.Fail = "Tài khoản hoặc mật khẩu không chính xác.";
                return View("Dangnhap");
            }

        }
        public ActionResult DangXuat()
        {
            Session["use"] = null;
            return RedirectToAction("Index", "Home");

        }

        public ActionResult Profile(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDQuyen = new SelectList(db.PhanQuyens, "IDQuyen", "TenQuyen", taiKhoan.IDQuyen);
            return View(taiKhoan);
        }

        // POST: Admin/Nguoidungs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNguoiDung,HoTen,Email,Dienthoai,Matkhau,IDQuyen,Diachi")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                //@ViewBag.show = "Chỉnh sửa hồ sơ thành công";
                //return View(nguoidung);
                return RedirectToAction("Profile", new { id = taiKhoan.MaNguoiDung });

            }
            ViewBag.IDQuyen = new SelectList(db.PhanQuyens, "IDQuyen", "TenQuyen", taiKhoan.IDQuyen);
            return View(taiKhoan);
        }
        public static byte[] encryptData(string data)
        {
            System.Security.Cryptography.MD5CryptoServiceProvider md5Hasher = new System.Security.Cryptography.MD5CryptoServiceProvider();
            byte[] hashedBytes;
            System.Text.UTF8Encoding encoder = new System.Text.UTF8Encoding();
            hashedBytes = md5Hasher.ComputeHash(encoder.GetBytes(data));
            return hashedBytes;
        }
        public static string md5(string data)
        {
            return BitConverter.ToString(encryptData(data)).Replace("-", "").ToLower();
        }
    }
}

QLCuaHangThoiTrang/CHBHTH/Views/User63133125/Dangky.cshtml
@model QLCuaHangThoiTrang_63133125.Models.TaiKhoan

@{ ViewBag.Title = "Dangky";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
    var useReg = Session["useReg"] as QLCuaHangThoiTrang_63133125.Models.TaiKhoan;
}

<div class="container">
    <h2 style="color: #CC9966">Đăng ký tài khoản VNZClothers-Shop</h2>
    <h3>@ViewBag.RegOk</h3>

    @{
        if (ViewBag.isReg == true)
        {
            <button class="btn-warning"> <a href="/User63133125/Dangnhap"> Đăng nhập</a> </button>
        }
    }

    @using (Html.BeginForm("Dangky", "User63133125", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { type = "Password", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.IDQuyen, "IDQuyen", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IDQuyen", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDQuyen, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group  my-2 py-2">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Đăng ký" class="btn btn-warning" />
                </div>
            </div>
        </div>
    }


</div>

QLCuaHangThoiTrang/CHBHTH/Views/User63133125/Dangnhap.cshtml
@model QLCuaHangThoiTrang_63133125.Models.LoginModel

@{ ViewBag.Title = "Dangnhap";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <style>
        main {
            background-color: #f8f9fa;
            color: #343a40;
            padding: 40px 0;
        }

        h2, h3 {
            color: #CC9966;
        }

        p {
            line-height: 1.6;
        }

        ul {
            list-style-type: disc;
            margin-left: 20px;
        }

        li {
            margin-bottom: 10px;
        }

        /* Container Styles */
        .container {
            margin: 0 auto;
        }

        ul li {
            list-style: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Hãy đăng nhập để sử dụng đầy đủ tính năng của Website</h2>
        <br />

        <h3 class="text-danger">@ViewBag.Fail</h3>

        @using (Html.BeginForm("Dangnhap", "User63133125", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.userMail, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.userMail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.userMail, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { type = "Password", @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group my-2 py-2">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Đăng nhập" class="btn btn-warning" />
                    </div>
                </div>
            </div>}


        @*<div>
            @Html.ActionLink("Back to List", "Index")
        </div>*@

    </div>
</body>
</html>

QLCuaHangThoiTrang/CHBHTH/Views/User63133125/Edit.cshtml
@model QLCuaHangThoiTrang_63133125.Models.TaiKhoan
<script src="~/Content/ckeditor/ckeditor.js"></script>
<script src="~/Content/ckfinder/ckfinder.js"></script>
<script src="~/Scripts/jquery-3.4.1.slim.js"></script>
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}

<center>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h2 style="color: #CC9966;">Chỉnh sửa hồ sơ cá nhân</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaNguoiDung)

            <div class="form-group">
                @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu thông tin" class="btn btn-warning" />
                </div>
            </div>
            <h3 style="color:red">@ViewBag.show</h3>
        </div>
    }
</center>

QLCuaHangThoiTrang/CHBHTH/Views/User63133125/Profile.cshtml
@model QLCuaHangThoiTrang_63133125.Models.TaiKhoan

@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_LayoutClient2.cshtml";
}

<center>
    <h2 style="color: #CC9966;"> Thông tin cá nhân khách hàng </h2>
    <br />
    <table class="table-hover table-bordered divGioHang">
        <tr style="">
            <th> Họ & tên</th>

            <th> Email </th>

            <th> Số điện thoại </th>

            <th> Mật khẩu </th>

            <th> Địa chỉ </th>

        </tr>

        <tr class="font-italic">
            <td>  @Html.DisplayFor(model => model.HoTen)</td>

            <td>  @Html.DisplayFor(model => model.Email) </td>

            <td>  @Html.DisplayFor(model => model.DienThoai)</td>

            <td>  @Html.DisplayFor(model => model.MatKhau)</td>

            <td>  @Html.DisplayFor(model => model.DiaChi)</td>
        </tr>


        <tr>
            <td colspan="5" style="text-align:right">
                <button class="btn btn-warning">
                    @Html.ActionLink("Xem đơn hàng", "Index", "Donhangs63133125", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" })
                </button>
                <button class="btn btn-secondary">
                    @Html.ActionLink("Chỉnh sửa hồ sơ", "Edit", new { id = Model.MaNguoiDung }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" })
                </button>
            </td>
        </tr>
    </table>
</center>
<br />

@*Css giỏ hàng*@
<style type="text/css">
    .divGioHang {
        border: 2px solid #EEEEEE;
        margin-left: 10%;
        font-size: large
    }

        .divGioHang td {
            padding: 40px;
            border: 2px solid #EEEEEE;
            text-align: center
        }

        .divGioHang th {
            text-align: center
        }
</style>